/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Reservation;

import UserInterface.Customer.*;
import UserInterface.Airliner.*;
import Business.Airliner.Airliner;
import Business.Airliner.Flight;
import Business.Customer.Customer;
import Business.Customer.Reservation;
import Business.TravelAgency.TravelAgency;
import UserInterface.Reservation.UpdateReservationScreen;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TeamCodeHater
 */
public class ViewAllReservationScreen extends javax.swing.JPanel {

    private JPanel rightPanel;
    private TravelAgency agency;

    /**
     * Creates new form AgentMainScreen
     */
    public ViewAllReservationScreen(JPanel rightPanel, TravelAgency agency) {
        initComponents();
        this.rightPanel = rightPanel;
        this.agency = agency;
        this.populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProducts = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();

        btnBack.setText("<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tabProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight Number", "Date", "Departure Time", "Arrival Time", "FromTo", "Seat", "Customer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabProducts);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setText("View All Reservations");

        btnCancel.setText("Delete");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnChange.setText("Change Seat");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(282, 282, 282)
                                .addComponent(btnChange)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnChange))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        this.rightPanel.remove(this);
        layout.show(this.rightPanel, "AgentMain");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabProducts.getSelectedRow();

        if (selectedRow >= 0) {
            Reservation info = (Reservation) tabProducts.getValueAt(selectedRow, 0);
            Customer cust = this.agency.getCustomerDir().getCustomer((String) tabProducts.getValueAt(selectedRow, 6));
            cust.getReservedList().remove(info);
            Flight f = this.agency.searchFlightByNum(info.getFlightNo());
            f.cancelBook(info.getRow(), info.getCol());
            JOptionPane.showMessageDialog(null, "Reservation deleted.");
            this.populate();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabProducts.getSelectedRow();

        if (selectedRow >= 0) {
            Reservation info = (Reservation) tabProducts.getValueAt(selectedRow, 0);
            Customer customer = this.agency.getCustomerDir().getCustomer((String) tabProducts.getValueAt(selectedRow, 6));
            Flight f = this.agency.searchFlightByNum(info.getFlightNo());
            UpdateReservationScreen view = new UpdateReservationScreen(this.rightPanel, this.agency, f, info, customer, "ViewAllReservationScreen");
            this.rightPanel.add("AirlinerViewScreen", view);
            CardLayout layout = (CardLayout) this.rightPanel.getLayout();
            layout.next(this.rightPanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) tabProducts.getModel();
        dtm.setRowCount(0);
        for (Customer c : this.agency.getCustomerDir().getCustomers()) {
            for (Reservation res : c.getReservedList()) {
                Flight i = this.agency.getAirlinerDir().getFlightByNum(res.getFlightNo());
                if (i != null) {
                    Object row[] = new Object[7];
                    row[0] = res;
                    SimpleDateFormat formatterDay = new SimpleDateFormat("MM/dd/yy");
                    SimpleDateFormat formatterTimeOfDay = new SimpleDateFormat("HH:mm:ss");
                    row[1] = formatterDay.format(i.getFlightDate());
                    row[2] = formatterTimeOfDay.format(i.getDepartureTime());
                    row[3] = formatterTimeOfDay.format(i.getArrivalTime());
                    row[4] = i.getDepartureLoc() + "-" + i.getArrivalLoc();
                    row[5] = "Row:" + res.getRow() + " Col:" + res.getCol();
                    row[6] = c.getFirstName()+" "+c.getLastName();
                    dtm.addRow(row);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tabProducts;
    // End of variables declaration//GEN-END:variables
}
