/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import UserInterface.Customer.ManageCustomer;
import UserInterface.Airliner.AirlinerMngScreen;
import Business.Airliner.Airliner;
import Business.Customer.Customer;
import Business.TravelAgency.TravelAgency;
import UserInterface.Reservation.SearchFlightsScreen;
import UserInterface.Reservation.ViewAllReservationScreen;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TeamCodeHater
 */
public class AgentMain extends javax.swing.JPanel {

    private JPanel rightPanel;
    private TravelAgency agency;
    /**
     * Creates new form CustomerMain
     */
    public AgentMain(JPanel rightPanel,TravelAgency agency) {
        initComponents();
        this.rightPanel=rightPanel;
        this.agency=agency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAirMng = new javax.swing.JButton();
        btnCustMng = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnResv = new javax.swing.JButton();

        btnAirMng.setText("Manage Airliners");
        btnAirMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirMngActionPerformed(evt);
            }
        });

        btnCustMng.setText("Manage Customers");
        btnCustMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustMngActionPerformed(evt);
            }
        });

        btnBook.setText("Book a flight");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnResv.setText("Manage Reservations");
        btnResv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBook, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(btnResv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAirMng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(376, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(btnCustMng, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(374, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnAirMng)
                .addGap(28, 28, 28)
                .addComponent(btnBook)
                .addGap(27, 27, 27)
                .addComponent(btnResv)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(btnCustMng)
                    .addContainerGap(321, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustMngActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.add("ManageCustomer",new ManageCustomer(rightPanel,agency));
        layout.next(rightPanel);
    }//GEN-LAST:event_btnCustMngActionPerformed

    private void btnAirMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirMngActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.add("AirlinerMngScreen",new AirlinerMngScreen(rightPanel,agency));
        layout.next(rightPanel);
    }//GEN-LAST:event_btnAirMngActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.add("SearchFlightsScreen",new SearchFlightsScreen(rightPanel,agency,"AgentMain"));
        layout.next(rightPanel);
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnResvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResvActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.add("ViewAllReservationScreen",new ViewAllReservationScreen(rightPanel,agency));
        layout.next(rightPanel);
    }//GEN-LAST:event_btnResvActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirMng;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCustMng;
    private javax.swing.JButton btnResv;
    // End of variables declaration//GEN-END:variables
}
