/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import UserInterface.Customer.ManageCustomer;
import UserInterface.Airliner.AirlinerMngScreen;
import Business.Airliner.Airliner;
import Business.Customer.Customer;
import Business.TravelAgency.TravelAgency;
import UserInterface.Customer.ViewReservationScreen;
import UserInterface.Reservation.SearchFlightsScreen;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TeamCodeHater
 */
public class CustomerMain extends javax.swing.JPanel {

    private JPanel rightPanel;
    private TravelAgency agency;
    private Customer cust;
    /**
     * Creates new form CustomerMain
     */
    public CustomerMain(JPanel rightPanel,TravelAgency agency,Customer cust) {
        initComponents();
        this.rightPanel=rightPanel;
        this.agency=agency;
        this.cust=cust;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewReseration = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();

        btnViewReseration.setText("View Reservation");
        btnViewReseration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReserationActionPerformed(evt);
            }
        });

        btnBook.setText("Book a flight");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewReseration, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(btnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnViewReseration)
                .addGap(78, 78, 78)
                .addComponent(btnBook)
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewReserationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReserationActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.add("ViewReservationScreen",new ViewReservationScreen(rightPanel,agency,cust));
        layout.next(rightPanel);
    }//GEN-LAST:event_btnViewReserationActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.add("SearchFlightsScreen",new SearchFlightsScreen(rightPanel,agency,"CustomerMain"));
        layout.next(rightPanel);
    }//GEN-LAST:event_btnBookActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnViewReseration;
    // End of variables declaration//GEN-END:variables
}
