/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Customer.Customer;
import Business.TravelAgency.TravelAgency;
import UserInterface.Reservation.SearchFlightsScreen;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TeamCodeHater
 */
public class LoginScreen extends javax.swing.JPanel {

    private JPanel rightPanel;
    private String userType;
    private TravelAgency agency;
    /**
     * Creates new form Login
     */
    public LoginScreen(JPanel rightPanel,String userType,TravelAgency agency) {
        initComponents();
        this.rightPanel=rightPanel;
        this.userType=userType;
        this.agency=agency;
        this.lblWelcome.setText(userType+" login");
        if(userType.equals("Customer"))
        {
            lbl1.setText("Username(FirstName LastName)");
            lbl2.setText("Passport Number");
        }
        else
        {
            lbl1.setText("Username");
            lbl2.setText("Password");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPW = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        lblWelcome.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lblWelcome.setText("login");

        lbl1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl1.setText("Username");

        lbl2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl2.setText("Password");

        btnLogin.setText("login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLogin))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWelcome)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPW, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblWelcome)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(txtPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnLogin)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if(this.userType.equals("Agent"))
        {
            if(this.txtName.getText().equals("admin")&&this.txtPW.getText().equals("admin"))
            {
                CardLayout layout = (CardLayout)rightPanel.getLayout();
                rightPanel.add("AgentMain",new AgentMain(rightPanel,agency));
                layout.next(rightPanel);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid username and password combination!");  
            }
        }
        else if(this.userType.equals("Customer"))
        {
            String name=txtName.getText();
            String passportNum=txtPW.getText();
            
            if(this.agency.getCustomerDir().exist(name,passportNum))
            {
                Customer cust=this.agency.getCustomerDir().getCustomer(name,passportNum);
                CardLayout layout = (CardLayout)rightPanel.getLayout();
                rightPanel.add("CustomerMain",new CustomerMain(rightPanel,agency,cust));
                layout.next(rightPanel);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid username and password combination!");  
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPW;
    // End of variables declaration//GEN-END:variables
}
