/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import Business.Airliner.Airliner;
import Business.Airliner.Airplane;
import Business.Airliner.Flight;
import Business.Customer.Customer;
import Business.TravelAgency.TravelAgency;
import UserInterface.Customer.ManageCustomer;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TeamCodeHater
 */
public class CreateFlightScreen extends javax.swing.JPanel {

    private JPanel rightPanel;
    private TravelAgency agency;
    private int index;
    private Flight f;
    private boolean airplaneSelected = false;

    /**
     * Creates new form CreateCustomerScreen
     */
    public CreateFlightScreen(JPanel rightPanel, TravelAgency agency, int index) {
        initComponents();
        this.rightPanel = rightPanel;
        this.agency = agency;
        this.index = index;
        f = new Flight();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        txtNumber = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDepTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDepLoc = new javax.swing.JTextField();
        txtArrLoc = new javax.swing.JTextField();
        txtArrTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSelectPlane = new javax.swing.JButton();
        lblAirplane = new javax.swing.JLabel();

        jLabel2.setText("Date(MM/dd/yy)");

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.setActionCommand("Update");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel1.setText("Flight Number");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Create New Flight");
        jLabel7.setToolTipText("");

        txtDepTime.setToolTipText("Format: mm/dd/yy");

        jLabel3.setText("Departure Time(hh:mm:ss)");

        jLabel4.setText("Departure Location");

        txtArrTime.setToolTipText("Format: mm/dd/yy");

        jLabel5.setText("Arrival Time(hh:mm:ss)");

        jLabel6.setText("Arrival Location");

        jLabel8.setText("Airplane");

        btnSelectPlane.setText("Select");
        btnSelectPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPlaneActionPerformed(evt);
            }
        });

        lblAirplane.setText("Airplane");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCreate)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtDepTime, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDepLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel4)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtArrTime, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(134, 134, 134)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnSelectPlane)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblAirplane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(txtArrLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel6))))))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDepTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArrTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArrLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnSelectPlane)
                    .addComponent(lblAirplane))
                .addGap(18, 18, 18)
                .addComponent(btnCreate)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        this.rightPanel.remove(this);
        Component[] comps = this.rightPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageFlightsScreen) {
                ManageFlightsScreen manageP = (ManageFlightsScreen) comp;
                manageP.populate();
            }
        }
        layout.show(this.rightPanel, "ManageFlightsScreen");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String number = this.txtNumber.getText();
        String date = this.txtDate.getText();
        String depTime = this.txtDepTime.getText();
        String depLoc = this.txtDepLoc.getText();
        String arrTime = this.txtArrTime.getText();
        String arrLoc = this.txtArrLoc.getText();
        Date d, depT, arrT;

        SimpleDateFormat formatterDay = new SimpleDateFormat("MM/dd/yy");
        SimpleDateFormat formatterTimeOfDay = new SimpleDateFormat("HH:mm:ss");
        try {
            
            d = formatterDay.parse(date);
            depT = formatterTimeOfDay.parse(depTime);
            arrT = formatterTimeOfDay.parse(arrTime);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid DATE/TIME format!");
            return;
        }
        
        if(!depT.before(arrT))
        {
            JOptionPane.showMessageDialog(null, "Arrival Time MUST BE after Departure Time!");
            return;
        }
        if(depLoc.equals(arrLoc))
        {
            JOptionPane.showMessageDialog(null, "Arrival location and departure location can’t be the same!");
            return;
        
        }
        if(this.agency.isFlightExist(number))
        {
            JOptionPane.showMessageDialog(null, "Flight number existed!");
            return;
        }

        f.setArrivalLoc(arrLoc);
        f.setArrivalTime(arrT);
        f.setDepartureLoc(depLoc);
        f.setDepartureTime(depT);
        f.setFlightDate(d);
        f.setFlightNum(number);
        int rows=f.getAirplane().getSeatRows();
        int cols=f.getAirplane().getSeatCols();
        f.setSeats(new int[rows][cols]);

        if (airplaneSelected) {
            if(isOverlapped(f))
            {
                JOptionPane.showMessageDialog(null, "An airplane can’t be assigned to two flights which have overlaps!Please select another plane.");
                return;
            }
            else{
            this.agency.getAirlinerDir().getAirlinerList().get(index).getSchedule().getFlights().add(f);
            f=new Flight();
            JOptionPane.showMessageDialog(null, "New flight created successfully!!");
            this.txtArrLoc.setText("");
            this.txtArrTime.setText("");
            this.txtDate.setText("");
            this.txtDepLoc.setText("");
            this.txtDepTime.setText("");
            this.txtNumber.setText("");
            this.airplaneSelected=false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an airplane!");
        }

    }//GEN-LAST:event_btnCreateActionPerformed

    private boolean isOverlapped(Flight newFlight)
    {
        for(Flight flight:this.agency.getAirlinerDir().getAirlinerList().get(index).getSchedule().getFlights())
        {
            if(!flight.getAirplane().getAirplaneID().equals(newFlight.getAirplane().getAirplaneID()))
                continue;
            else if(flight.getFlightDate().compareTo(newFlight.getFlightDate())!=0)
                continue;
            else if(flight.getArrivalTime().before(newFlight.getDepartureTime())||flight.getDepartureTime().after(newFlight.getArrivalTime()))
                continue;
            else
            //当已经存在航班的飞机与新添加的航班的飞机相同，且时间有交叉时，返回true
            if((flight.getArrivalTime().after(newFlight.getDepartureTime())||flight.getDepartureTime().before(newFlight.getArrivalTime())))
                return true;
        }
        return false;
    }
    private void btnSelectPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPlaneActionPerformed
        // TODO add your handling code here:
        this.airplaneSelected = true;
        SelectAirplaneScreen select = new SelectAirplaneScreen(this.rightPanel, this.agency, this.index, this.f);
        
        this.rightPanel.add("SelectAirplaneScreen", select);
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        layout.next(this.rightPanel);

    }//GEN-LAST:event_btnSelectPlaneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSelectPlane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel lblAirplane;
    private javax.swing.JTextField txtArrLoc;
    private javax.swing.JTextField txtArrTime;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDepLoc;
    private javax.swing.JTextField txtDepTime;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
